name: Push-to-EC2

on:
  push:
    branches:
      - main  # or your specific branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "/home/ec2-user/aasu-bot"

      - name: Execute Python script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd /home/ec2-user/aasu-bot
            tmux has-session -t aasu 2>/dev/null || tmux new-session -d -s aasu
            # Activate the virtual environment and run the script in tmux
            tmux send-keys -t aasu "source venv/bin/activate" C-m
            tmux send-keys -t aasu "pip install -r requirements.txt" C-m
            tmux send-keys -t aasu "python3 src/bot.py" C-m
